name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: action/checkout@v2
      
      - name: build test on a container
        run: docker build -t gotest .
        
      - name: run test on a container 
        run: docker run gotest
