name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo hello
          
#       - name: checkout repo
#         uses: action/checkout@v3
#         with:
#           token: ${{ secrets.MY_TOKEN }}
      
      - name: build test on a container
        run: docker build -t gotest .
        
      - name: run test on a container 
        run: docker run gotest
